### ISSUE TITLE
Closure compile is not minified (doesn't use optimizations)

### ISSUE THREAD

**Issue by evmar** [samccone/The-cost-of-transpiling-es2015-in-2016#22]
You have to pass a flag to closure to make it minify.  Your example with the screenshot in the readme shows it isn't minified.

If you change your makefile to pass --compilation_level ADVANCED_OPTIMIZATIONS, your closure JS size is halved.

However, you'll often need additional source annotations to get the advanced optimizations to apply.  I haven't verified whether this project does that.  But there is little reason to use the closure compiler if you're not using its advanced optimizations, as it generates pretty verbose code otherwise.

**Comment by samccone** [comment]
Hi @martine thanks for the issue, currently the source code does not work when I pass ADVANCED_OPTIMIZATIONS as a flag without breaking the app.

I am working on updating the source code to allow this type of mangling across all of the tools.

Thanks for the issue and thoughts.

**Comment by evmar** [comment]
Closure without any optimizations is like babel without uglify, so it makes no sense to compare it to the things you've compared it to in your graph.

Note how in your pictures in the readme the babel+browserify example has lots of short variable names, while the Closure one has the excessively long ones like `a$$module$demo$a`.  That name is effectively a compiler-internal name that isn't intended to be surfaced in real code.

Just to show how silly it is: I noticed in the code in your repo if you look at the compiled output it generates nonsense variable names like `Model$$module$__$src$src$model`.  To restate, the compiler is written to intentionally generate extra-verbose code because it is implied that a later pass will reduce it.

Don't get me wrong -- I'm not a huge fan of the Closure compiler -- but it bugs me to see bad information about their project published.  I think the fair thing to do would be to leave them out of your analysis until you have time to set it up.

PS: I'm a little confused why you closed this bug, because your numbers are wrong and the issue remains.  But it's your bug tracker.  :)

**Comment by samccone** [comment]
Thanks for the feedback I am actively working on making things able to be mangled.

from the main writeup

>  (no code was changed to help any compilers perform better).

I disagree that the numbers are incorrect -- rather they are representative of what was possible without modifying the code, thus I closed the issue.

Thanks again and any help is more than welcome.

**Comment by samccone** [comment]
Also I have been talked to @matrixfrog prior to publish time and given the constraints of no code changes (for the initial version of the data) these results do not represent "bad information"

**Comment by MatrixFrog** [comment]
If `no code was changed to help any compilers perform better` is a hard requirement then you're not going to get much out of Closure in terms of code size reduction. If you're willing to make some small changes (or use a different codebase to test on -- more on that later), then you can probably get advanced mode turned on. The issues I've found that make the code not be Closure-Compiler-friendly (as discussed on chat, but it'll be nice to have them captured here) are:
1. [View.viewCommands](https://github.com/samccone/The-cost-of-transpiling-es2015-in-2016/blob/master/src/src/view.js#L64) is being used as an `Object<string, Function>` (its keys are accessed as strings) so it should be written with quoted keys so that the compiler won't rename them:
   
   this.viewCommands = {
      'showEntries': parameter => this.$todoList.innerHTML = this.template.show(parameter),
      'removeItem': parameter => this._removeItem(parameter),
      etc
2. The `todos` property of the object that is serialized to `localStorage` will be renamed. When I tried it, it was renamed to `j`: [This line](https://github.com/samccone/The-cost-of-transpiling-es2015-in-2016/blob/master/src/src/store.js#L61) became something like `a.call(this, JSON.parse(localStorage[this.b]).j);`. The compiler renaming is not stable, so if it renames to `j` now it might rename to `k` in a future version of your code, and then the new code won't be able to retrieve values stored by the old code. When putting values into `localStorage` or similar, you need to always use quoted keys (or there are other approaches, like `@export`)

There are probably other such things but these are the two I found so far. I guess I personally would like more clarity on what the goal of this repo is. Your README mentions tree-shaking but this is a very small app with no external dependencies so there isn't much dead code to eliminate. A better test might be to include a lot of external dependencies but only use one small function from each of them (though if those dependencies aren't Closure-friendly then you'll still run into some problems). Or, take a fairly large existing app that already uses Closure Compiler, and start introducing ES6 features to see if adding more and more ES6 causes the codesize to increase significantly. We have several apps at Google doing this but I don't know of any that are open source, unfortunately :(

Closure Compiler works best if you read the [Compiler Assumptions](https://github.com/google/closure-compiler/wiki/Compiler-Assumptions) page before writing any code, and also if you type-annotate all your code and enable type-based optimizations. If the target audience for this repo is a team that is willing to do that because they're going to be writing a large app and want it to be typechecked and analyzable and refactorable, then you should use a JS sample that adheres to those assumptions. If the target audience is a smaller app, or someone who is used to some of the more dynamic aspects of JavaScript, then Closure Compiler may not be the best tool for them.

**Comment by samccone** [comment]
here are the new numbers

thanks for all the help and input!

![image](https://cloud.githubusercontent.com/assets/883126/12774181/38ca7d68-c9f7-11e5-9f7a-6fe1cfad0118.png)

**Comment by concavelenz** [comment]
At the very least you want to use --assume_function_wrapper which enable the same kind of assumption as rollup is making.

**Comment by samccone** [comment]
:+1: ah cool TIL thanks @concavelenz
